alias ll='ls -al'
alias ping='ping -c 5'
alias mkdir='mkdir -p'
alias vimrc='vim ~/.vim/vimrc'
alias bashrc='vim ~/.bashrc'
alias zshrc='vim ~/.zshrc'
alias antigenrc='vim ~/.antigenrc'
alias it='git'
alias 'cd.'='cd ..'
alias 'cd..'='cd ..'
alias less='less -FX'
alias dmesg='dmesg -L'
alias https='http --verify=no --default-scheme=https'
alias vim='mvim -v'
alias tmux='tmux -2'
alias asciicast2gif='npx -p asciicast2gif asciicast2gif'
alias ff='/Applications/Firefox\ Developer\ Edition.app/Contents/MacOS/firefox -new-tab'
alias kafdrop='ff localhost:9000'
